//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Generator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///// AbstractFactory - 0
        /////{AbstractProductA} - 1
        /////{AbstractProductB} - 2
        /////{ProductA1} - 3
        /////{ProductA2} - 4
        /////{ProductB1} - 5
        /////{ProductB2} - 6
        /////{ConcreteFactory1} - 7
        /////{ConcreteFactory2} - 8
        /////{Client} - 9
        /////{Run} - 10
        /////{CreateProductA} -11
        /////{CreateProductB} - 12
        /////{Interact} - 13
        ///namespace {0}
        ///{{
        ///    abstract class {0}
        ///    {{
        ///        public abstract {1} {11}();
        ///        public abstract {2} {12}();
        ///    }}
        ///
        ///    abstract class {1}
        ///    {{
        ///    }}
        ///
        ///    abstract cla [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AbstactFactory {
            get {
                return ResourceManager.GetString("AbstactFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        /////Abstraction - 0
        /////Implementor - 1
        /////RefinedAbstraction - 2
        /////ConcreteImplementorA - 3
        /////ConcreteImplementorB - 4
        /////Operation - 5
        /////OperationImp - 6
        ///namespace Bridge
        ///{
        ///    abstract class {0}
        ///    {
        ///        protected {1} implementor = null;
        ///
        ///        public {0}({1} implementor)
        ///        {
        ///            this.implementor = implementor;
        ///        }
        ///
        ///        public virtual void {5}()
        ///        {
        ///            implementor.{6}();
        ///        }
        ///    }
        ///
        ///    abstract class {1}
        ///    {
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bridge {
            get {
                return ResourceManager.GetString("Bridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        /////{Builder} - {0}
        /////{Director} - 1
        /////{ConcreteBuilder} - 2
        /////{Product} - 3
        /////{GetResult} -4
        /////{BuildPartA} -5
        /////{BuildPartB} -6
        /////{BuildPartC} -7
        /////{Construct} -8
        /////{Show} -9
        ///namespace {0}
        ///{{
        ///    abstract class {0}
        ///    {{
        ///        public abstract void {5}();
        ///        public abstract void {6}();
        ///        public abstract void {7}();
        ///        public abstract {3} {4}();
        ///    }}
        ///
        ///    class {1}
        ///    {{
        ///        {0} builder;
        ///
        ///        public {1}({0} builder)
        ///        {{
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Builder {
            get {
                return ResourceManager.GetString("Builder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        /////Handler - 0
        /////ConcreteHandler1 - 1
        /////ConcreteHandler2 - 2
        /////HandleRequest - 3
        /////Successor - 4
        ///namespace Chain
        ///{
        ///    abstract class {0}
        ///    {
        ///        public {0} {4} { get; set; }
        ///        public abstract void {3}(int request);
        ///    }
        ///
        ///    class {1} : {0}
        ///    {
        ///        public override void {3}(int request)
        ///        {
        ///            if (request == 2)
        ///            {
        ///                //...
        ///            }
        ///            else if ({4} != null)
        ///                {4}.{3}(request);
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChainOfResponsibility {
            get {
                return ResourceManager.GetString("ChainOfResponsibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        /////Adapter - 0
        /////ITarget - 1
        /////Adaptee - 2
        /////Request - 3
        /////SpecificRequest - 4
        ///namespace {0}
        ///{
        ///    class {0} : {2}, {1}
        ///    {
        ///        public void {3}()
        ///        {
        ///            base.{4}();
        ///        }
        ///    }
        ///
        ///    interface {1}
        ///    {
        ///        void {3}();
        ///    }
        ///
        ///    class {2}
        ///    {
        ///        public void {4}()
        ///        {
        ///           //...
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string ClassAdapter {
            get {
                return ResourceManager.GetString("ClassAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        /////ConcreteCommand - 0
        /////Invoker - 1
        /////Receiver - 2
        /////Action - 3
        ///namespace PatternCommand
        ///{
        ///    abstract class Command
        ///    {
        ///        protected {2} receiver;
        ///
        ///        public Command({2} receiver)
        ///        {
        ///            this.receiver = receiver;
        ///        }
        ///
        ///        public abstract void Execute();
        ///    }
        ///
        ///    class {0} : Command
        ///    {
        ///        public {0}({2} receiver)
        ///            : base(receiver)
        ///        {
        ///        }
        ///
        ///        public override void Execute()
        ///        {
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections;
        ///
        /////Composite - 0
        /////Component - 1
        /////Leaf - 2
        /////Operation - 3
        /////GetChild - 4
        ///namespace {0}
        ///{
        ///    abstract class {1}
        ///    {
        ///        protected string name;
        ///
        ///        public {1}(string name)
        ///        {
        ///            this.name = name;
        ///        }
        ///
        ///        public abstract void {3}();
        ///        public abstract void Add({1} component);
        ///        public abstract void Remove({1} component);
        ///        public abstract {1} {4}(int index);
        ///    }
        ///
        ///    class {0} : {1}
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Composite {
            get {
                return ResourceManager.GetString("Composite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        /////Decorator - 0
        /////Component - 1
        /////ConcreteComponent - 2
        /////ConcreteDecoratorA - 3
        /////ConcreteDecoratorB - 4
        /////Operation - 5
        /////AddedBehavior - 6
        ///namespace {0}
        ///{
        ///    abstract class {0} : {1}
        ///    {
        ///        public {1} {1} { protected get; set; }
        ///
        ///        public override void {5}()
        ///        {
        ///            if ({1} != null)
        ///                {1}.{5}();
        ///        }
        ///    }
        ///
        ///    abstract class {1}
        ///    {
        ///        public abstract void {5}();
        ///    }
        ///
        ///    class {2} : {1}
        ///    {
        ///        pub [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Decorator {
            get {
                return ResourceManager.GetString("Decorator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        /////Facade - 0
        /////SubSystemA - 1
        /////SubSystemB - 2
        /////SubSystemC - 3
        /////OperationA - 4
        /////OperationB - 5
        /////OperationC - 6
        /////OperationAB - 7
        /////OperationBC - 8
        ///namespace {0}
        ///{
        ///    class {0}
        ///    {
        ///        {1} subSystemA = new {1}();
        ///        {2} subSystemB = new {2}();
        ///        {3} subSystemC = new {3}();
        ///
        ///        public void {7}()
        ///        {
        ///            subSystemA.{4}();
        ///            subSystemB.{5}();
        ///        }
        ///
        ///        public void {8}()
        ///        {
        ///            subSystemB.{5}();
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Facade {
            get {
                return ResourceManager.GetString("Facade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        /////FactoryMethod - 0
        /////Creator - 1
        /////Product - 2
        /////ConcreteCreator - 3
        /////ConcreteProduct - 4
        /////AnOperation - 5
        ///namespace {0}
        ///{{   
        ///    abstract class {1}
        ///    {{
        ///        {2} product;
        ///
        ///        public abstract {2} {0}();
        ///
        ///        public void {5}()
        ///        {{
        ///            product = {0}();
        ///        }}
        ///    }}
        ///
        ///    abstract class {2}
        ///    {{
        ///    }}
        ///
        ///    class {3} : {1}
        ///    {{
        ///        public override {2} {0}()
        ///        {{
        ///            return new {4}();
        ///        }}
        ///    }}
        ///
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FactoryMethod {
            get {
                return ResourceManager.GetString("FactoryMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        /////Flyweight - 0
        /////ConcreteFlyweight - 1
        /////UnsharedConcreteFlyweight - 2
        /////FlyweightFactory - 3
        /////Operation - 4
        /////GetConcreteFlyweight - 5
        /////GetUnsharedConcreteFlyweight - 6
        ///namespace {0}
        ///{
        ///    abstract class {0}
        ///    {
        ///        public abstract void {4}(ConsoleColor extrinsicState);
        ///    }
        ///
        ///    class {1} : {0}
        ///    {
        ///        string intrinsicState = &quot;{1} &quot;;
        ///        ConsoleColor extrinsicState;
        ///
        ///        public override void {4}(ConsoleColor extrinsicState)
        ///        {
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Flyweight {
            get {
                return ResourceManager.GetString("Flyweight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        /////Context - 0
        /////AbstractExpression - 1
        /////NonterminalExpression - 2
        /////TerminalExpression - 3
        /////Interpret - 4
        /////Source - 5
        /////Vocabulary - 6
        /////Result - 7
        /////Position - 8
        ///namespace Interpreter
        ///{
        ///    class {0}
        ///    {
        ///        public string {5} { get; set; }
        ///        public char {6} { get; set; }
        ///        public bool {7} { get; set; }
        ///        public int {8} { get; set; }
        ///    }
        ///
        ///    abstract class {1}
        ///    {
        ///        public abstract void {4}({0} context);
        ///    }
        ///
        ///    class {2} : {1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Interpreter {
            get {
                return ResourceManager.GetString("Interpreter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        /////Iterator - 0
        /////Aggregate - 1
        /////ConcreteIterator - 2
        /////ConcreteAggregate - 3
        /////CreateIterator - 4
        /////First - 5
        /////Next - 6
        /////IsDone - 7
        /////CurrentItem - 8
        ///namespace {0}
        ///{
        ///    abstract class {0}
        ///    {
        ///        public abstract object {5}();
        ///        public abstract object {6}();
        ///        public abstract bool {7}();
        ///        public abstract object {8}();
        ///    }
        ///
        ///    abstract class {1}
        ///    {
        ///        public abstract {0} {4}();
        ///        public abstract int Count { get; }
        ///        pu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Iterator {
            get {
                return ResourceManager.GetString("Iterator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections;
        ///
        /////Enumerator - 0
        /////Enumerable - 1
        ///namespace {0}
        ///{
        ///    class {1} : IEnumerable
        ///    {
        ///        private ArrayList items = new ArrayList();
        ///        public object this[int index]
        ///        {
        ///            get { return items[index]; }
        ///            set { items.Insert(index, value); }
        ///        }
        ///        public int Count
        ///        {
        ///            get { return items.Count; }
        ///        }
        ///    
        ///        public IEnumerator GetEnumerator()
        ///        {
        ///            return new {0}(this);
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IteratorNET {
            get {
                return ResourceManager.GetString("IteratorNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        /////Singleton - 0
        /////Instance - 1
        ///namespace {0}
        ///{{
        ///    class {0}
        ///    {{
        ///        static Lazy&lt;{0}&gt; instance = new Lazy&lt;{0}&gt;();
        ///
        ///        public static {0} {1}
        ///        {{
        ///            get
        ///            {{
        ///                return instance.Value;
        ///            }}
        ///        }}
        ///    }}
        ///}}
        ///.
        /// </summary>
        internal static string LazySingleton {
            get {
                return ResourceManager.GetString("LazySingleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        /////Mediator - 0
        /////Colleague - 1
        /////ConcreteColleague1 - 2
        /////ConcreteColleague2 - 3
        /////ConcreteMediator - 4
        /////Send - 5
        /////Notify - 6
        ///namespace {0}
        ///{
        ///    abstract class {0}
        ///    {
        ///        public abstract void {5}(string message, {1} colleague);
        ///    }
        ///
        ///    abstract class {1}
        ///    {
        ///        protected {0} mediator;
        ///
        ///        public {1}({0} mediator)
        ///        {
        ///            this.mediator = mediator;
        ///        }
        ///    }
        ///
        ///    class {2} : {1}
        ///    {
        ///        public {2}({0} mediator)
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mediator {
            get {
                return ResourceManager.GetString("Mediator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        /////Memento - 0
        /////Caretaker - 1
        /////Originator - 2
        /////SetMemento - 3
        /////CreateMemento - 4
        /////State - 5
        ///namespace {0}
        ///{
        ///    class {0}
        ///    {
        ///        public string {5} { get; private set; }
        ///
        ///        public {0}(string state)
        ///        {
        ///            this.{5} = state;
        ///        }
        ///    }
        ///
        ///    class {1}
        ///    {
        ///        public {0} {0} { get; set; }
        ///    }
        ///
        ///    class {2}
        ///    {
        ///        public string {5} { get; set; }
        ///
        ///        public void {3}({0} memento)
        ///        {
        ///            {5} = memen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Memento {
            get {
                return ResourceManager.GetString("Memento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Threading;
        ///
        /////Singleton - 0
        /////Instance - 1
        ///namespace {0}
        ///{{
        ///    class {0}
        ///    {{
        ///        private static volatile {0} instance;
        ///        private static Mutex mutex = new Mutex();
        ///
        ///        private {0}() {{ }}
        ///
        ///        public static {0} {1}
        ///        {{
        ///            get
        ///            {{
        ///                Thread.Sleep(500);
        ///
        ///                if (instance == null)
        ///                {{
        ///                    mutex.WaitOne();
        ///
        ///                    if (instance == null)
        ///                        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MultiThreadedSingleton {
            get {
                return ResourceManager.GetString("MultiThreadedSingleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///
        /////Adapter - 0
        /////Target - 1
        /////Adaptee - 2
        /////Request - 3
        /////SpecificRequest - 4
        ///namespace {0}
        ///{
        ///    abstract class {1}
        ///    {
        ///        public abstract void {3}();
        ///    }
        ///
        ///    class {0} : {1}
        ///    {
        ///        {2} adaptee = new {2}();
        ///
        ///        public override void {3}()
        ///        {
        ///            adaptee.{4}();
        ///        }
        ///    }
        ///
        ///    class {2}
        ///    {
        ///        public void {4}()
        ///        {
        ///            // ...
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string ObjectAdapter {
            get {
                return ResourceManager.GetString("ObjectAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections;
        ///
        /////Observer - 0
        /////Subject - 1
        /////ConcreteSubject - 2
        /////ConcreteObserver - 3
        /////Update - 4
        /////Attach - 5
        /////Detach - 6
        /////Notify - 7
        ///namespace {0}
        ///{
        ///    abstract class {0}
        ///    {
        ///        public abstract void {4}();
        ///    }
        ///
        ///    abstract class {1}
        ///    {
        ///        ArrayList observers = new ArrayList();
        ///
        ///        public void {5}({0} observer)
        ///        {
        ///            observers.Add(observer);
        ///        }
        ///
        ///        public void {6}({0} observer)
        ///        {
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Observer {
            get {
                return ResourceManager.GetString("Observer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///
        /////Observer - 0
        /////Subject - 1
        /////ConcreteSubject - 2
        /////Notify - 3
        /////State - 4
        /////Event - 5
        ///namespace {0}
        ///{
        ///    delegate void {0}(string state);  
        ///
        ///    abstract class {1}
        ///    {
        ///        protected {0} observers = null;
        ///
        ///        public event {0} {5}
        ///        {
        ///            add { observers += value; }
        ///            remove { observers -= value; }
        ///        }
        ///
        ///        public abstract string {4} { get; set; }
        ///        public abstract void {3}();
        ///    }  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ObserverEvent {
            get {
                return ResourceManager.GetString("ObserverEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///
        /////ConcreteObserver - 0
        /////ConcreteSubject - 1
        /////Unsubscriber - 2
        /////Notify - 3
        /////State - 4
        ///// - 5
        ///// - 6
        ///namespace Observer
        ///{
        ///    class {0} : IObserver&lt;string&gt;
        ///    {
        ///        string name;
        ///        string observerState;
        ///        IDisposable unsubscriber;
        ///
        ///        public {0}(string name, IObservable&lt;string&gt; subject)
        ///        {
        ///            this.name = name;
        ///            unsubscriber = subject.Subscribe(this);
        ///        }        
        ///
        ///        public vo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ObserverNET {
            get {
                return ResourceManager.GetString("ObserverNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        /////Prototype - 0
        ///namespace {0}
        ///{{
        ///   class {0} : ICloneable
        ///    {{        
        ///        public string State {{ get; set; }}
        ///
        ///        public {0} Clone()
        ///        {{
        ///            return this.MemberwiseClone() as {0};
        ///        }}
        ///    }}
        ///}}
        ///.
        /// </summary>
        internal static string Prototype {
            get {
                return ResourceManager.GetString("Prototype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        /////Proxy - 0
        /////RealSubject - 1
        /////Subject - 2
        /////Request - 3
        ///namespace {0}
        ///{
        ///    class {0} : {2}
        ///    {
        ///        {1} realSubject;
        ///
        ///        public override void {3}()
        ///        {
        ///            if (realSubject == null)
        ///                realSubject = new {1}();
        ///
        ///            realSubject.{3}();
        ///        }
        ///    }
        ///
        ///    abstract class {2}
        ///    {
        ///        public abstract void {3}();
        ///    }
        ///
        ///    class {1} : {2}
        ///    {
        ///        public override void {3}()
        ///        {
        ///            //...
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Proxy {
            get {
                return ResourceManager.GetString("Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.ServiceModel;
        ///
        /////ISubject - 0
        /////RealSubject - 1
        /////Client - 2
        /////Server - 3
        /////Say - 4
        ///namespace Ambassador
        ///{    
        ///    [ServiceContract]
        ///    interface {0}
        ///    {
        ///        [OperationContract]
        ///        void {4}(string input);
        ///    }
        ///
        ///    class {1} : {0}
        ///    {
        ///        public void {4}(string input)
        ///        {
        ///            Console.WriteLine(&quot;Got: &quot; + input);
        ///        }
        ///    }
        ///
        ///    class {2}
        ///    {
        ///        static void Run()
        ///        {
        ///            Console.Title = &quot;CLIENT&quot;; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProxyAmbassador {
            get {
                return ResourceManager.GetString("ProxyAmbassador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        /////Proxy - 0
        /////Subject - 1
        /////RealSubject - 2
        /////Create - 3
        /////Read - 4
        /////Update - 5
        /////Delete - 6
        ///namespace {0}
        ///{
        ///    abstract class {1}
        ///    {
        ///        public abstract void {3}(string key, string value);
        ///        public abstract string {4}(string key);
        ///        public abstract bool {5}(string key, string value);
        ///        public abstract bool {6}(string key);
        ///    }
        ///
        ///    class {0} : {1}
        ///    {
        ///        {1} subject;
        ///        string role;
        ///
        ///        public {0}({1} subject, string role) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProxyCRUD {
            get {
                return ResourceManager.GetString("ProxyCRUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        /////Singleton - 0
        /////Instance - 0
        ///namespace {0}
        ///{{
        ///    class {0}
        ///    {{
        ///        static {0} uniqueInstance;
        ///
        ///        protected {0}()
        ///        {{
        ///        }}
        ///
        ///        public static {0} {1}()
        ///        {{
        ///            if (uniqueInstance == null)
        ///                uniqueInstance = new {0}();
        ///
        ///            return uniqueInstance;
        ///        }}        
        ///    }}
        ///}}
        ///.
        /// </summary>
        internal static string Singleton {
            get {
                return ResourceManager.GetString("Singleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        /////State - 0
        /////Context - 1
        /////ConcreteStateA - 2
        /////ConcreteStateB - 3
        /////Handle - 4
        /////Request - 5
        ///namespace {0}
        ///{
        ///    abstract class {0}
        ///    {
        ///        public abstract void {4}({1} context);
        ///    }
        ///
        ///    class {1}
        ///    {
        ///        public {0} {0} { get; set; }
        ///
        ///        public {1}({0} state)
        ///        {
        ///            this.{0} = state;
        ///        }
        ///
        ///        public void {5}()
        ///        {
        ///            this.{0}.{4}(this);
        ///        }
        ///    }
        ///
        ///    class {2} : {0}
        ///    {
        ///        public overri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        /////Strategy - 0
        /////ConcreteStrategyA - 1
        /////ConcreteStrategyB - 2
        /////ConcreteStrategyC - 3
        /////Context - 4
        /////AlgorithmInterface - 5
        /////ContextInterface - 6
        ///namespace {0}
        ///{
        ///    abstract class {0}
        ///    {
        ///        public abstract void {5}();
        ///    }
        ///
        ///    class {1} : {0}
        ///    {
        ///        public override void {5}()
        ///        {
        ///           //...
        ///        }
        ///    }
        ///
        ///    class {2} : {0}
        ///    {
        ///        public override void {5}()
        ///        {
        ///            //...
        ///        }
        ///    }
        ///
        ///    class {3} : { [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Strategy {
            get {
                return ResourceManager.GetString("Strategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        /////AbstractClass - 0
        /////ConcreteClass - 1
        /////PrimitiveOperation1 - 2
        /////PrimitiveOperation2 - 3
        /////TemplateMethod - 4
        ///namespace Template
        ///{
        ///    abstract class {0}
        ///    {
        ///        public abstract void {2}();
        ///        public abstract void {3}();
        ///
        ///        public void {4}()
        ///        {
        ///            {2}();
        ///            {3}();
        ///        }
        ///    }
        ///
        ///    class {1} : {0}
        ///    {
        ///        public override void {2}()
        ///        {
        ///            //...
        ///        }
        ///
        ///        public override void {3}()
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TemplateMethod {
            get {
                return ResourceManager.GetString("TemplateMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        /////Visitor - 0
        /////Element - 1
        /////ObjectStructure - 2
        /////ConcreteElementA - 3
        /////ConcreteElementB - 4
        /////ConcreteVisitor1 - 5
        /////ConcreteVisitor2 - 6
        /////VisitConcreteElementA - 7
        /////VisitConcreteElementB - 8
        /////Accept - 9
        /////OperationA - 10
        /////OperationB - 11
        ///namespace {0}
        ///{
        ///    abstract class {0}
        ///    {
        ///        public abstract void {7}({3} elementA);
        ///        public abstract void {8}({4} elementB);
        ///    }
        ///
        ///    abstract class {1}
        ///    {
        ///        public abstract void {9}({0} visitor);
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Visitor {
            get {
                return ResourceManager.GetString("Visitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections;
        ///
        /////Enumerable - 0
        ///namespace Yield
        ///{
        ///    class {0}
        ///    {
        ///        public IEnumerator GetEnumerator()
        ///        {
        ///            yield return &quot;Element&quot;;
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string YieldIterator {
            get {
                return ResourceManager.GetString("YieldIterator", resourceCulture);
            }
        }
    }
}
